


var projects=[
    {id:1,name:"Amas 1",description:"Near To King Saud Bin Abdulaziz University For Health Sciences.Near To King Fahd Stadium.Adjacent to main roads.Surrounded by all consumer services.(Supermarkets, restaurants, cafes, etc.)",site:"Riyadh - Qadisiyah",status:"sold",area:"2900",type:"apartment",nobuilding:"26",nounits:20,nounitsava:16,listbuilding:"A B",gallery:["build1.jpeg","build2.png","build3.jpeg","build4.jpeg","build5.jpeg"]},
    {id:2,name:"Amas 2",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Al Izdihar",status:"forsale",area:"800",type:"villa",nobuilding:"1",nounits:"1",nounitsava:"1",listbuilding:"A",gallery:["build5.jpeg","build1.jpeg","build2.png","build3.jpeg","build4.jpeg"]},
    {id:3,name:"Amas 3",description:"Close to Mouwasat Hospital, Granada Mall and Al Izdihar Center Complex. The neighborhood is characterized by the presence of many international schools.",site:"Riyadh - Narjis",status:"sold",area:"500",type:"villa",nobuilding:"1",nounits:"1",nounitsava:"1",listbuilding:"B",gallery:["build4.jpeg","build5.jpeg","build1.jpeg","build2.png","build3.jpeg"]},
    {id:4,name:"Amas 4",description:"Close to Mouwasat Hospital, Granada Mall and Al Izdihar Center Complex. The neighborhood is characterized by the presence of many international schools.",site:"Riyadh - Qurtubah",status:"forsale",area:"250",type:"apartment",nobuilding:"10",nounits:"10",nounitsava:"10",listbuilding:"A",gallery:["build3.jpeg","build4.jpeg","build5.jpeg","build1.jpeg","build2.png"]},
    {id:5,name:"Amas 5",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Narjis",status:"sold",area:"300",type:"villa",nobuilding:"1",nounits:"1",nounitsava:"1",listbuilding:"B",gallery:["build2.png","build3.jpeg","build4.jpeg","build5.jpeg","build1.jpeg"]},
    {id:6,name:"Amas 6",description:"Close to Mouwasat Hospital, Granada Mall and Al Izdihar Center Complex. The neighborhood is characterized by the presence of many international schools.",site:"Riyadh - Qurtubah",status:"forsale",area:"1900",type:"apartment",nobuilding:"20",nounits:"18",nounitsava:"12",listbuilding:"B",gallery:["build1.jpeg","build2.png","build3.jpeg","build4.jpeg","build5.jpeg"]},
    {id:7,name:"Amas 7",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Qadisiya",status:"forsale",area:"600",type:"villa",nobuilding:"1",nounits:"1",nounitsava:"1",listbuilding:"A",gallery:["build5.jpeg","build1.jpeg","build2.png","build3.jpeg","build4.jpeg"]},
    {id:8,name:"Amas 8",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Qurtubah",status:"forsale",area:"760",type:"apartment",nobuilding:"3",nounits:"10",nounitsava:"6",listbuilding:"A",gallery:["build4.jpeg","build5.jpeg","build1.jpeg","build2.png","build3.jpeg"]},
    {id:9,name:"Amas 9",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Al Izdihar",status:"sold",area:"690",type:"villa",nobuilding:"1",nounits:"1",nounitsava:"1",listbuilding:"B",gallery:["build3.jpeg","build4.jpeg","build5.jpeg","build1.jpeg","build2.png"]},
    {id:10,name:"Amas 10",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Qurtubah",status:"forsale",area:"200",type:"villa",nobuilding:"1",nounits:"1",nounitsava:"1",listbuilding:"B",gallery:["build2.png","build3.jpeg","build4.jpeg","build5.jpeg","build1.jpeg"]},
    {id:11,name:"Amas 11",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Qurtubah",status:"forsale",area:"350",type:"apartment",nobuilding:"1",nounits:"6",nounitsava:"5",listbuilding:"A",gallery:["build1.jpeg","build2.png","build3.jpeg","build4.jpeg","build5.jpeg"]},
    {id:12,name:"Amas 12",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Narjis",status:"sold",area:"1500",type:"apartment",nobuilding:"6",nounits:"12",nounitsava:"10",listbuilding:"B",gallery:["build5.jpeg","build1.jpeg","build2.png","build3.jpeg","build4.jpeg"]},
    {id:13,name:"Amas 13",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Narjis",status:"forsale",area:"1800",type:"villa",nobuilding:"1",nounits:"1",nounitsava:"1",listbuilding:"A",gallery:["build4.jpeg","build5.jpeg","build1.jpeg","build2.png","build3.jpeg"]},
    {id:14,name:"Amas 14",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Al Izdihar",status:"sold",area:"1600",type:"apartment",nobuilding:"3",nounits:"15",nounitsava:"13",listbuilding:"A",gallery:["build3.jpeg","build4.jpeg","build5.jpeg","build1.jpeg","build2.png"]},
    {id:15,name:"Amas 15",description:"Close to Princess Noura University and King Abdullah Hospital / adjacent to the main roads and surrounded by all consumer services (supermarkets, restaurants, cafes...etc)",site:"Riyadh - Qadisiyah",status:"sold",area:"930",type:"villa",nobuilding:"1",nounits:"1",nounitsava:"1",listbuilding:"B",gallery:["build2.png","build3.jpeg","build4.jpeg","build5.jpeg","build1.jpeg"]}
];
var news=[
    {id:1,title:"The Best Places To Start Your Local Listing",date:"22/1/2022",writer:"Administrator",description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",img:"new-img.png",tag:"Finace, Business, Money, Markets, Investing, Economy"},
    {id:2,title:"The Best Places To Start Your Local Listing",date:"22/1/2022",writer:"Administrator",description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",img:"new-img.png",tag:"Finace, Business, Money, Markets, Investing, Economy"},
    {id:3,title:"The Best Places To Start Your Local Listing",date:"22/1/2022",writer:"Administrator",description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",img:"new-img.png",tag:"Finace, Business, Money, Markets, Investing, Economy"},
    {id:4,title:"The Best Places To Start Your Local Listing",date:"22/1/2022",writer:"Administrator",description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",img:"new-img.png",tag:"Finace, Business, Money, Markets, Investing, Economy"},
    {id:5,title:"The Best Places To Start Your Local Listing",date:"22/1/2022",writer:"Administrator",description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",img:"new-img.png",tag:"Finace, Business, Money, Markets, Investing, Economy"},
    {id:6,title:"The Best Places To Start Your Local Listing",date:"22/1/2022",writer:"Administrator",description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",img:"new-img.png",tag:"Finace, Business, Money, Markets, Investing, Economy"},
    {id:7,title:"The Best Places To Start Your Local Listing",date:"22/1/2022",writer:"Administrator",description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",img:"new-img.png",tag:"Finace, Business, Money, Markets, Investing, Economy"},
    {id:8,title:"The Best Places To Start Your Local Listing",date:"22/1/2022",writer:"Administrator",description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",img:"new-img.png",tag:"Finace, Business, Money, Markets, Investing, Economy"},
    {id:9,title:"The Best Places To Start Your Local Listing",date:"22/1/2022",writer:"Administrator",description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",img:"new-img.png",tag:"Finace, Business, Money, Markets, Investing, Economy"}


];